# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e753378b722d29091be0367ead1147805c5a3c911f791559c95c577b032393e4e72f052220a4ca90d1ac91c2ea5d267f6eeac2a6c9cb88de069171243938e05c

test:
  secret_key_base: 5843558118d72b616cf2493526896a17672d06cfd293ac90bcf7ba513ee23f7c6d2902c91e14366892a3378e14039f9123e27073fac56da99b63de7ba292e311

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
